backend:
  namespace: backend
  replicas: 1
  containerPort: 3000
  image: learnerreportbackend:latest
  secrets:
    ATLAS_URI: "mongodb+srv://aseem:VfPuqBChLeCu0U@cluster0.aorqndq.mongodb.net/blog_merne?retryWrites=true&w=majority"
    HASH_KEY: "thisIsMyHashKey"
    JWT_SECRET_KEY: "thisIsMyJwtSecretKey"
  resources:
    limits:
      memory: "512Mi"
      cpu: "500m"
    requests:
      memory: "256Mi"
      cpu: "250m"

frontend:
  namespace: frontend
  replicas: 1
  containerPort: 3000
  image: learnerreportfrontend:latest
  resources:
    limits:
      memory: "512Mi"
      cpu: "500m"
    requests:
      memory: "256Mi"
      cpu: "250m"
