backend:
  namespace: backend
  replicas: 1
  containerPort: 3000
  image: learnerreportbackend:latest
  secrets:
    ATLAS_URI: "bW9uZ29kYitzcnY6Ly9hc2VlbTpXZlB1cWFCY0hsZWN1MFV0QGNsdXN0ZXIwLmFvcnFuZHEubW9uZ29kYi5uZXQvYmxvZ19tZXJuP3JldHJ5V3JpdGVzPXRydWUmdz1tYWpvcml0eQ=="
    HASH_KEY: "dGhpc0lzTXlIYXNoS2V5"
    JWT_SECRET_KEY: "dGhpc0lzTXlKd3RTZWNyZXRLZXk"
  resources:
    limits:
      memory: "512Mi"
      cpu: "500m"
    requests:
      memory: "256Mi"
      cpu: "250m"

frontend:
  namespace: frontend
  replicas: 1
  containerPort: 3000
  image: learnerreportfrontend:latest
  resources:
    limits:
      memory: "512Mi"
      cpu: "500m"
    requests:
      memory: "256Mi"
      cpu: "250m"
